osx_image: xcode8.1
language: objective-c
env:
  matrix:
    - PLATFORM=iOS SDK=iphonesimulator SCHEME=TrueTime-iOS DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=10.0"
    - PLATFORM=Mac SDK=macosx SCHEME=TrueTime-Mac DESTINATION="platform=macOS"
    - PLATFORM=tvOS SDK=appletvsimulator SCHEME=TrueTime-tvOS DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0"
install: 
  - gem install xcpretty
  - brew install swiftlint
  - carthage bootstrap --platform "$PLATFORM" --no-use-binaries
script:
  - Scripts/test
cache:
  directories:
    - Carthage/Build
